var questoes = [
    {
        prova: "Revalida 2022",
        area: "Clínica Médica",
        tema: "Bradiarritmias",
        pergunta: "Um paciente de 64 anos foi levado por familiares à unidade de emergência logo após ter apresentado episódio de síncope. Segundo o paciente, ele já tinha apresentado 2 outros episódios nos últimos 3 meses, sempre precedidos por sensação de “tonteiras”, e, eventualmente, tem sentido a impressão de fraqueza, “escurecimento da visão” e sensação de queda iminente. Não há dados relevantes de história patológica pregressa do paciente, que não faz uso de nenhum fármaco regularmente. No exame físico, o paciente apresentava-se bradicárdico (42 batimentos por minuto), normotenso, com ritmo cardíaco regular em 3 tempos (B4), sem sopros. Seu pulso venoso jugular revelou a presença de intermitentes ondas “a em canhão”. Foi realizado um eletrocardiograma, que revelou padrão similar ao ilustrado na figura Acima. O emergencista que atende esse paciente deverá explicar-lhe que será necessária a realização de ",
        imagem: "revalida_2022/ecg-batv.png",
        alternativas: [
            "cardioversão elétrica.",
            "ablação de via anômala.",
            "implante de marca-passo definitivo.",
            "isolamento elétrico das vias pulmonares. "
        ],
        correta: 2,
        comentarios: [
    "<strong>❌ INCORRETA.</strong><br><br><strong>📌 O erro principal:</strong> A cardioversão elétrica sincronizada é indicada EXCLUSIVAMENTE para taquiarritmias instáveis (ex: TV com pulso, FA com alta resposta > 150 bpm).<br><br><strong>🔍 Por que não serve aqui?</strong><br>Paciente está com 42 bpm (BRADICARDIA extrema), normotenso, mas com síncope prévia. A cardioversão não restaura a condução AV em um bloqueio total.<br><br><strong>✅ Conduta correta na emergência:</strong> Estabilização com atropina (se instável) e, após confirmação de BAVT, encaminhar para implante de marca-passo. Não se aplica choque elétrico em bradicardia.",

    "<strong>❌ INCORRETA.</strong><br><br><strong>📌 O erro principal:</strong> A ablação de via anômala trata TAQUIARRITMIAS (ex: Síndrome de WPW, taquicardia por reentrada nodal).<br><br><strong>🔍 Achado-chave do caso:</strong> As ondas <em>\"a em canhão\"</em> no pulso venoso jugular são PATOGNOMÔNICAS de dissociação atrioventricular (átrio e ventrículo contraindo separadamente).<br><br><strong>⚠️ Fique atento:</strong> O problema aqui é uma falha de condução no sistema His-Purkinje (BAVT), e não uma via acessória extra. Fazer ablação nesse cenário não resolveria a bradicardia e ainda poderia piorar a condução nativa.",

    "<strong>✅ ALTERNATIVA CORRETA.</strong><br><br><strong>📌 Motivo principal:</strong> Paciente com Bloqueio Atrioventricular Total (3º grau) sintomático, comprovado por síncope, bradicardia extrema (42 bpm) e ondas <em>\"a em canhão\"</em>.<br><br><strong>🔬 Fundamentação:</strong> O ECG deve mostrar ondas P sem relação com os QRS (dissociação completa). Segundo as Diretrizes da SBC e ACC/AHA, o implante de marca-passo definitivo é Classe I, Nível A para prevenir síncope e morte súbita.<br><br><strong>💡 Dica de ouro:</strong> Ondas \"a em canhão\" + bradicardia grave + síncope = BAVT = MARCA-PASSO!",


    "<strong>❌ INCORRETA.</strong><br><br><strong>📌 O erro principal:</strong> Isolamento elétrico das veias pulmonares (ablação de FA) é indicado para FIBRILAÇÃO ATRIAL paroxística ou persistente (TAQUIARRITMIA).<br><br><strong>🔍 Por que está errado?</strong><br>O paciente tem ritmo REGULAR (não é fibrilação, que é irregularmente irregular) e está BRADICÁRDICO. O procedimento é feito no átrio esquerdo e não atua no nó AV ou sistema de His, que são os responsáveis pela bradicardia.<br><br><strong>⚠️ Macete para prova:</strong> Sempre que ouvir \"veias pulmonares\" → pense em FA. Sempre que ouvir \"onda a em canhão\" → pense em BAVT e marca-passo!"
]
    },
    {
        prova: "Revalida 2022",
        area: "Cirurgia",
        tema: "Hiperplasia Prostática Benigna e Câncer de Bexiga",
        pergunta: "Homem de 75 anos de idade, tabagista 1 maço/dia desde os 20 anos de idade, apresenta queixa de polaciúria, disúria e hematúria macroscópica. Relata diversos episódios de infecção do trato urinário no passado e hiperplasia prostática benigna tratada por ressecção transuretral, com melhora significativa dos sintomas obstrutivos urinários. No toque retal, percebe-se próstata de tamanho aumentado, com superfície regular. Exame de urina tipo I (EAS) evidencia hematúria maciça, com mais de 80% de hemácias isomórficas. Nesse caso, a melhor conduta diagnóstica e o diagnóstico mais provável são, respectivamente",
        alternativas: [
            "uretrocistoscopia; carcinoma invasor de bexiga.",
            "urografia excretora; carcinoma de células renais.",
            "ressonância magnética de abdome; cálculo coraliforme.",
            "ultrassom transretal com biópsia de próstata; adenocarcinoma de próstata."
        ],
        correta: 0,
        comentarios: [
    "<strong>✅ ALTERNATIVA CORRETA.</strong><br><br><strong>📌 Motivo principal:</strong> Homem idoso (75 anos), TABAGISTA PESADO (55 anos-maço) com hematúria macroscópica e hemácias > 80% ISOMÓRFICAS.<br><br><strong>🔬 Raciocínio passo a passo:</strong><br>1) Hemácias isomórficas = sangramento NÃO glomerular (descartamos rim).<br>2) Tabagismo + idade + hematúria = principal hipótese é CÂNCER DE BEXIGA (carcinoma urotelial).<br>3) A URETROCISTOSCOPIA é o padrão-ouro, pois permite visualizar toda a mucosa vesical e biopsiar a lesão.<br><br><strong>💡 Fique atento:</strong> Nenhum exame de imagem (TC, USG, RM) substitui a visão direta da bexiga na hematúria macroscópica suspeita.",

    "<strong>❌ INCORRETA.</strong><br><br><strong>📌 O erro principal:</strong> A urografia excretora (UIV) é um exame antigo e com baixa sensibilidade para tumores de bexiga, principalmente lesões planas (carcinoma in situ).<br><br><strong>🔍 Por que o diagnóstico de CCR está errado?</strong><br>O carcinoma de células renais (rim) classicamente cursa com tríde: hematúria + dor lombar + massa abdominal. O enunciado fala em POLACIÚRIA e DISÚRIA (sintomas vesicais), sem dor lombar.<br><br><strong>✅ Exame correto para suspeita de CCR:</strong> TC de abdome com contraste em fases (não a urografia excretora). Descartamos com segurança.",

    "<strong>❌ INCORRETA.</strong><br><br><strong>📌 O erro principal:</strong> A Ressonância Magnética NÃO é o exame de primeira linha para cálculos renais. O padrão-ouro é a TC de abdome e pelve SEM contraste.<br><br><strong>🔍 Por que o cálculo coraliforme não se encaixa?</strong><br>Cálculos coraliformes costumam cursar com DOR LOMBAR intensa, infecção urinária de repetição por germes produtores de urease (Proteus) e febre. O paciente tem hematúria \"fria\" (assintomática), sem dor lombar.<br><br><strong>⚠️ Dica:</strong> A RM não visualiza bem a maioria dos cálculos (oxalato de cálcio e fosfato). A conduta aqui seria TC, não RM.",

    "<strong>❌ INCORRETA.</strong><br><br><strong>📌 O erro principal:</strong> A biópsia de próstata (TRUS) é indicada para SUSPEITA DE CÂNCER DE PRÓSTATA (PSA elevado + toque retal suspeito).<br><br><strong>🔍 O que contradiz a alternativa?</strong><br>O toque retal mostrou PRÓSTATA AUMENTADA com SUPERFÍCIE REGULAR – isso é típico de HPB, NÃO de adenocarcinoma (que seria nodular, irregular e assimétrica). Além disso, câncer de próstata localizado raramente causa hematúria macroscópica franca.<br><br><strong>✅ Conduta correta:</strong> O verdadeiro problema é a bexiga, e não a próstata. Fazer biópsia aqui seria iatrogênico e atrasaria o diagnóstico do tumor vesical."
]   
    },
    {
        prova: "Revalida 2022",
        area: "Pediatria",
        tema: "Aleitamento e introdução alimentar",
        pergunta: "Lactente de 6 meses está sendo atendido na unidade básica de saúde para consulta de puericultura. A criança, nascida com 39 semanas, encontra-se em aleitamento materno exclusivo e com desenvolvimento neuropsicomotor adequado. Sua genitora solicita orientações para iniciar a alimentação complementar. Acerca da introdução alimentar nesse caso, assinale a opção correta. ",
        alternativas: [
            "A carne deve ser triturada e peneirada, para garantir oferta adequada de ferro, zinco e vitamina B12.",
            "As frutas, in natura, raspadas, amassadas ou picadas devem ser introduzidas como fontes de fibras.",
            "Os sucos devem ser introduzidos na rotina alimentar, uma vez ao dia, sendo importante fonte de vitaminas e fibras. ",
            "A gema do ovo, por ser uma importante fonte proteica, deve ser oferecida de imediato, ao passo que a clara, devido ao seu poder alergênico, deve ser oferecida somente após 12 meses de idade."
        ],
        correta: 1,
        comentarios: [
    "<strong>❌ INCORRETA.</strong><br><br><strong>📌 O erro principal:</strong> A carne NÃO deve ser peneirada! A peneiração/liquidificação elimina a textura, atrasando o desenvolvimento da mastigação e da coordenação motora oral.<br><br><strong>✅ O que fazer certo:</strong> Ofereça a carne moída, desfiada ou amassada com garfo, mantendo PEQUENOS GRUMINHOS. Crianças de 6 meses já manipulam alimentos macios com a gengiva.<br><br><strong>⚠️ Fique de olho:</strong> O Guia Alimentar do Ministério da Saúde (2019) e a SBP são enfáticos: nada de peneira ou liquidificador! A textura em pedaços é obrigatória a partir dos 6 meses.",

    "<strong>✅ ALTERNATIVA CORRETA.</strong><br><br><strong>📌 Motivo principal:</strong> Frutas devem ser oferecidas <em>in natura</em>, raspadas, amassadas com garfo ou picadas em pedaços bem pequenos.<br><br><strong>🔬 Fundamentação:</strong> Essa textura preserva as FIBRAS (previne constipação), estimula a mastigação e garante vitaminas, principalmente a Vitamina C, que auxilia na absorção do ferro.<br><br><strong>💡 Dica de ouro para a prova:</strong> Sucos são PROIBIDOS (perdem fibras e têm muito açúcar). A fruta é sempre oferecida inteira, amassada ou picada – NUNCA em forma de suco!",

    "<strong>❌ INCORRETA.</strong><br><br><strong>📌 O erro principal:</strong> Sucos NÃO devem ser introduzidos, nem mesmo uma vez ao dia.<br><br><strong>🔬 Evidência científica:</strong> O suco perde todas as fibras, concentra açúcares livres (frutose), aumentando o risco de cárie, obesidade infantil e substituindo refeições nutritivas.<br><br><strong>✅ Conduta correta:</strong> A única bebida além do leite materno é a ÁGUA. A fruta é oferecida no prato (amassada ou picada), nunca no copo ou mamadeira.",

    "<strong>❌ INCORRETA.</strong><br><br><strong>📌 O erro principal:</strong> Essa regra antiga de \"clara do ovo só depois de 12 meses\" é ULTRAPASSADA e contra as evidências atuais.<br><br><strong>🧬 Fundamentação:</strong> Estudos robustos (LEAP, EAT) provaram que introduzir o ovo INTEIRO (gema + clara) entre 4-6 meses REDUZ o risco de alergia (janela de tolerância imunológica).<br><br><strong>✅ Conduta correta:</strong> Ofereça o ovo COZIDO e inteiro (amassado) a partir dos 6 meses. Clara e gema juntas desde o início, observando sinais de reação, mas sem proibir."
]   
    },
    {
        prova: "Revalida 2022",
        area: "Ginecologia e Obstetrícia",
        tema: "Hemorragia Pós-parto",
        pergunta: "Adolescente de 14 anos de idade, primípara, em puerpério imediato de parto vaginal, apresenta sangramento vaginal abundante, sem morbidades associadas à gestação. No exame, ela apresentou: regular estado geral, frequência respiratória de 23 incursões por minuto; tempo de enchimento capilar de 6 segundos; frequência cardíaca de 128 batimentos por minuto; pressão arterial de 80 x 30 mmHg; abdome globoso, normotenso; útero contraído abaixo da cicatriz umbilical, sem lesões no canal de parto. Diante do quadro apresentado, assinale a opção que estabelece a conduta apropriada a ser adotada em conjunto com a reanimação.",
        alternativas: [
            "Administração de 800 mcg de misoprostol via retal.",
            "Indicação de laparotomia de urgência para histerectomia.",
            "Conduta expectante, mantendo-se a monitorização clínica.",
            "Exame da placenta e, caso estejam presentes escavações, indicação de curetagem uterina."
        ],
    correta: 3,
    comentarios: [
        "<strong>❌ INCORRETA.</strong><br><br><strong>📌 O erro principal:</strong> O misoprostol (análogo da prostaglandina E1) é a droga de primeira linha para o tratamento da ATONIA UTERINA (útero flácido, não contraído). Porém, o enunciado é taxativo: o útero está CONTRAÍDO abaixo da cicatriz umbilical.<br><br><strong>🔍 Por que está errado usar aqui?</strong><br>Se o útero já está contraído, a hemorragia não é causada por falha de contratilidade do miométrio. Administrar misoprostol nesse cenário é inócuo (não vai estancar o sangramento) e atrasa o diagnóstico da verdadeira causa.<br><br><strong>✅ Conduta correta para atonia:</strong> Se fosse atonia, usaríamos ocitocina, metilergonovina e misoprostol. Mas aqui o quadro é outro! Descartamos com segurança.",

        "<strong>❌ INCORRETA.</strong><br><br><strong>📌 O erro principal:</strong> A histerectomia periparto é uma medida EXTREMA e mutiladora, reservada apenas para casos de hemorragia incontrolável por rotura uterina, placenta acreta invasiva ou atonia refratária a todas as medidas clínico-cirúrgicas.<br><br><strong>🔍 Por que essa conduta é DESPROPORCIONAL aqui?</strong><br>O útero está íntegro (contraído, sem lesões no canal de parto) e o diagnóstico mais provável é a presença de restos placentários, que tem resolução com curetagem uterina (procedimento conservador e minimamente invasivo).<br><br><strong>⚠️ Fique atento:</strong> A conduta obstétrica deve ser sempre a menos invasiva possível para preservar a fertilidade, ainda mais em uma adolescente. Histerectomia seria um erro médico grave nesse contexto.",

        "<strong>❌ INCORRETA.</strong><br><br><strong>📌 O erro principal:</strong> Paciente com SINAIS DE CHOQUE HIPOVOLÊMICO GRAVE (FC 128 bpm, PA 80x30 mmHg, TEC 6 segundos). A conduta expectante é ABSOLUTAMENTE contraindicada em qualquer emergência obstétrica com instabilidade hemodinâmica.<br><br><strong>🔍 A fisiopatologia do choque:</strong> O sangramento abundante reduz o débito cardíaco, levando a hipoperfusão tecidual (TEC prolongado). Esperar a monitorização sem intervir ativamente aumenta o risco de choque irreversível, coagulopatia aguda (CIVD) e óbito materno.<br><br><strong>✅ O que fazer?</strong> Reanimar com volume (cristaloides, sangue) e, SIMULTANEAMENTE, investigar e tratar a causa mecânica do sangramento. Não se espera em hemorragia pós-parto!",

        "<strong>✅ ALTERNATIVA CORRETA.</strong><br><br><strong>📌 Motivo principal:</strong> A paciente apresenta um quadro clássico de Hemorragia Pós-parto (HPP) com ÚTERO CONTRAÍDO e canal de parto íntegro. Quando o útero está contraído e não há lacerações, a origem do sangramento é, obrigatoriamente, a loja placentária.<br><br><strong>🔬 Raciocínio passo a passo:</strong><br>1) <strong>Descartamos atonia</strong> (útero contraído) e <strong>descartamos lacerações</strong> (exame físico negativo).<br>2) A causa mais provável é a retenção de RESTOS PLACENTÁRIOS (escavações ou cotilédones retidos). Esses fragmentos impedem a contração efetiva da musculatura uterina naquele ponto específico, mantendo o sangramento.<br>3) A conduta é o EXAME MINUCIOSO DA PLACENTA (verificar se está completa, com todos os cotilédones e membranas) e, se forem encontradas escavações ou irregularidades na cavidade uterina, indicar a CURETAGEM UTERINA para remover os fragmentos e permitir a hemostasia definitiva.<br><br><strong>💡 Dica de ouro para a prova:</strong> <em>\"Sangramento pós-parto + útero contraído + via de parto íntegra = pense em restos placentários e faça curetagem!\"</em> Lembre-se de associar à reposição volêmica agressiva para tratar o choque hipovolêmico simultaneamente."
    ]
},
{
    prova: "Revalida 2022",
    area: "Clínica Médica",
    tema: "Transtornos psiquiatricos",
    pergunta: "Uma mulher de 34 anos com diagnóstico de depressão procurou a unidade de saúde da família (UBS) onde você trabalha. Com base no prontuário da paciente, você observou que ela faz acompanhamento na unidade há 10 meses com outro médico da unidade. A paciente consulta sozinha, mas chegou à unidade acompanhada da irmã, com quem ela mora e que está bastante preocupada. A paciente tem sintomas de humor deprimido, fatigabilidade e choro fácil; está em uso de 40 mg/dia de fluoxetina nos últimos 6 meses, tendo apresentado discreta melhora. Segundo a paciente, há 1 mês, aproximadamente, começou a ouvir vozes e ver alguns vultos, e tem pensado em se matar, mas sem plano. Nesse caso, qual é a conduta adequada?",
    alternativas: [
        "Continuar o atendimento na UBS e trocar o tratamento.",
        "Encaminhar a paciente para internação em hospital psiquiátrico.",
        "Solicitar internação em hospital geral e otimizar o tratamento farmacológico.",
        "Referenciar a paciente à equipe multiprofissional do Centro de Atenção Psicossocial."
    ],
    correta: 3,
    comentarios: [
        "<strong>❌ INCORRETA.</strong><br><br><strong>📌 O erro principal:</strong> A UBS é a porta de entrada da Rede de Atenção Psicossocial (RAPS) e pode manejar quadros leves a moderados de depressão e ansiedade. Porém, este caso é GRAVE e COMPLEXO: a paciente desenvolveu <strong>sintomas psicóticos (alucinações auditivas e visuais)</strong> e <strong>ideação suicida</strong> ativa (mesmo sem plano).<br><br><strong>🔍 Por que a troca do tratamento na UBS é insuficiente?</strong><br>A fluoxetina (ISRS) em dose plena (40 mg) já falhou em controlar os sintomas centrais e, pior, surgiram alucinações. Isso pode indicar um diagnóstico diferente (ex: depressão psicótica, transtorno bipolar em fase mista, ou até esquizofrenia incipiente). O manejo adequado necessita de <strong>avaliação psiquiátrica especializada</strong> para introdução de antipsicóticos e ajuste fino da terapêutica, algo que a UBS, via de regra, não tem estrutura nem expertise para fazer sozinha.<br><br><strong>✅ O que fazer?</strong> Acolher, estabilizar os sinais vitais, garantir a segurança imediata e <strong>referenciar ao CAPS</strong> (alternativa D). Manter na UBS seria subtratar e colocar a paciente em risco.",

        "<strong>❌ INCORRETA.</strong><br><br><strong>📌 O erro principal:</strong> A internação em hospital psiquiátrico (hospital especializado) é indicada apenas em situações de <strong>risco iminente e grave</strong>, como tentativa de suicídio recente, agressividade incontrolável, ou quando o paciente não tem suporte familiar e social adequado.<br><br><strong>🔍 Por que a internação é DESPROPORCIONAL aqui?</strong><br>A paciente tem ideação suicida, mas <strong>SEM PLANO</strong> (ou seja, não há intenção ou método definido). Além disso, ela mora com a irmã, que está preocupada e pode oferecer suporte. A Política Nacional de Saúde Mental prioriza a <strong>desinstitucionalização</strong> e o tratamento em liberdade. Internar precocemente uma paciente com esse perfil, sem tentar o manejo no CAPS primeiro, é considerado iatrogênico e vai contra as diretrizes do SUS.<br><br><strong>⚠️ Fique atento:</strong> Só interne se houver <em>\"risco iminente\"</em> (plano estruturado, comportamento autolesivo ativo, ou recusa de alimentação/hidratação). Esse não é o caso.",

        "<strong>❌ INCORRETA.</strong><br><br><strong>📌 O erro principal:</strong> A internação em hospital geral (enfermaria psiquiátrica em hospital geral) é indicada para quadros agudos que cursam com <strong>comprometimento clínico grave</strong>, como intoxicação exógena, delirium, ou quando o paciente apresenta condições médicas que justificam suporte hospitalar (ex: desnutrição severa, infecções).<br><br><strong>🔍 O que está errado aqui?</strong><br>A paciente não apresenta nenhuma morbidade clínica associada (está estável do ponto de vista orgânico). A \"otimização do tratamento farmacológico\" pode e deve ser feita no CAPS ou em regime de hospital-dia (CAPS III), sem a necessidade de ocupar um leito de hospital geral, que é um recurso escasso e caro para o SUS.<br><br><strong>✅ Conduta correta:</strong> A porta de entrada para quadros psiquiátricos graves, mas sem urgência clínica, é o <strong>CAPS</strong>. A internação em hospital geral seria uma \"sobrecarga\" desnecessária do sistema.",

        "<strong>✅ ALTERNATIVA CORRETA.</strong><br><br><strong>📌 Motivo principal:</strong> Esta é a conduta perfeitamente alinhada com os protocolos do Ministério da Saúde e a lógica da Rede de Atenção Psicossocial (RAPS). A paciente apresenta um quadro de <strong>depressão grave com sintomas psicóticos e ideação suicida</strong>, o que a torna elegível para acompanhamento no CAPS (nível de média/alta complexidade em saúde mental).<br><br><strong>🔬 Raciocínio passo a passo:</strong><br>1) A paciente tem <strong>sintomas psicóticos</strong> (vozes e vultos) – isso exige avaliação psiquiátrica com urgência para introdução de antipsicóticos (ex: quetiapina, risperidona) e reavaliação diagnóstica.<br>2) A <strong>ideação suicida sem plano</strong> não é uma urgência psiquiátrica que necessite internação imediata, mas é um <strong>fator de risco</strong> que demanda acompanhamento intensivo (consultas semanais ou diárias em CAPS).<br>3) O CAPS dispõe de <strong>equipe multiprofissional</strong> (psiquiatra, psicólogo, terapeuta ocupacional, assistente social), que pode ofertar atendimento individual, grupal, oficinas terapêuticas e, se necessário, internação parcial (CAPS III) ou monitoramento do risco de suicídio.<br>4) A referência para o CAPS <strong>não exclui</strong> o cuidado na UBS; a UBS deve continuar acompanhando a paciente em conjunto (matriciamento), mas a <strong>responsabilidade pelo tratamento especializado</strong> passa a ser do CAPS.<br><br><strong>💡 Dica de ouro para a prova:</strong> <em>\"Ideação suicida sem plano + sintomas psicóticos + falha do tratamento na UBS = encaminhamento ao CAPS\"</em>. Lembre-se: a internação só é indicada se houver <strong>plano ativo, tentativa recente ou descontrole agressivo</strong>. O CAPS é a via correta para a grande maioria dos quadros psiquiátricos graves na atenção básica!"
    ]
},
{
    prova: "Revalida 2022",
    area: "Clinica Médica",
    tema: "Hipertensão",
    pergunta: "Uma paciente de 62 anos de idade foi encaminhada ao ambulatório de nefrologia de um hospital universitário para ajuste no tratamento anti-hipertensivo, em razão de suposta nefropatia hipertensiva estágio 3. A paciente tem hipertensão arterial sistêmica (HAS) há longa data e faz tratamento com hidroclorotiazida 25 mg/dia e anlodipino 10 mg duas vezes ao dia. Recentemente, seus exames de sangue revelaram pequena retenção de escórias nitrogenadas, sendo o cálculo estimado da taxa de filtração glomerular de 54 ml/min/1,73 m². Exame urinário revelou a presença de microalbuminúria (120 mg/g de creatinina em amostra isolada de urina; valor de referência: até 30 mg/g de creatinina na urina). No exame físico, os níveis tensionais se encontravam em 150 x 90 mmHg no membro superior (MS) direito e em 148 x 92 mmHg no MS esquerdo. Considerando-se o risco cardiovascular da paciente, os níveis tensionais observados na consulta e a presença de dano renal crônico em estágio 3 (da classificação KDIGO — do inglês Kidney Disease: Improving Global Outcomes), em relação ao esquema terapêutico em curso, a conduta correta seria",
    alternativas: [
        "Adicionar inibidor da enzima conversora ou bloqueador do receptor de angiotensina II.",
        "Trocar a hidroclorotiazida por diurético de alça e aumentar a dose do bloqueador de canal de cálcio.",
        "Iniciar espironolactona e carvedilol.",
        "Mantê-lo sem alterações e trabalhar a adesão ao tratamento."
    ],
    correta: 0,
    comentarios: [
        "<strong>✅ ALTERNATIVA CORRETA.</strong><br><br><strong>📌 Motivo principal:</strong> A paciente tem DRC estágio 3 (TFG 54 ml/min) com microalbuminúria (120 mg/g) e HAS não controlada (PA 150/90 mmHg em uso de dois anti-hipertensivos). As diretrizes KDIGO 2021 e as diretrizes brasileiras de HAS recomendam, para pacientes com DRC e albuminúria, a <strong>adição de iECA (ex: enalapril, lisinopril) ou BRA (ex: losartana, valsartana)</strong> como parte do esquema anti-hipertensivo.<br><br><strong>🔬 Fundamentação científica:</strong><br>1) Os iECA/BRA promovem <strong>renoproteção</strong> ao reduzir a pressão intraglomerular (dilatação da arteríola eferente) e diminuir a albuminúria, retardando a progressão da DRC.<br>2) Além disso, esses fármacos têm <strong>benefício cardiovascular comprovado</strong> em pacientes de alto risco, reduzindo eventos como infarto e insuficiência cardíaca.<br>3) A paciente já faz uso de um diurético tiazídico (hidroclorotiazida) e um bloqueador de canal de cálcio (anlodipino). A adição de um iECA/BRA é o passo lógico para alcançar a meta pressórica (< 130/80 mmHg para DRC com albuminúria, segundo KDIGO) e oferecer proteção renal adicional.<br><br><strong>💡 Dica de ouro:</strong> Em todo paciente com DRC e albuminúria (relação albumina/creatinina > 30 mg/g), independentemente da etiologia, o uso de iECA ou BRA é <strong>Classe I, Nível de Evidência A</strong> – não pode faltar na prova!",

        "<strong>❌ INCORRETA.</strong><br><br><strong>📌 O erro principal:</strong> Trocar a hidroclorotiazida por diurético de alça (ex: furosemida) só é necessário quando a TFG é < 30 ml/min (DRC estágios 4-5), pois os tiazídicos perdem eficácia nessa faixa. Aqui a TFG é 54 ml/min (estágio 3), então a hidroclorotiazida ainda é efetiva.<br><br><strong>🔍 Outro erro:</strong> Aumentar a dose do anlodipino (Bloqueador de Canal de Cálcio – BCC) pode ser uma estratégia, mas <strong>substituir o diurético e aumentar o BCC sem adicionar iECA/BRA</strong> perde a oportunidade de oferecer a renoproteção específica que esses medicamentos proporcionam. Em pacientes com albuminúria, o iECA/BRA é obrigatório, e não pode ser omitido.<br><br><strong>⚠️ Fique atento:</strong> A troca por diurético de alça seria uma conduta inadequada e prematura, pois o estágio 3 ainda se beneficia de tiazídicos. A conduta correta é acrescentar o iECA/BRA, e não substituir os outros.",

        "<strong>❌ INCORRETA.</strong><br><br><strong>📌 O erro principal:</strong> Espironolactona (antagonista da aldosterona) e carvedilol (betabloqueador) não são medicamentos de primeira linha para hipertensão na DRC sem indicação específica.<br><br><strong>🔍 Quando usar espironolactona?</strong><br>A espironolactona pode ser considerada em casos de hipertensão resistente (já em uso de 3 ou mais anti-hipertensivos, incluindo diurético) ou em insuficiência cardíaca com fração de ejeção reduzida, mas <strong>não é a primeira escolha</strong> para um paciente que ainda não utiliza iECA/BRA, que é a classe com maior evidência de renoproteção.<br><br><strong>⚠️ O carvedilol</strong> é um betabloqueador útil em insuficiência cardíaca e pós-infarto, mas não tem indicação primária para HAS em DRC. Iniciar ambos sem necessidade expõe a paciente a efeitos colaterais (hipercalemia com espironolactona, bradicardia com carvedilol) sem o benefício fundamental da proteção renal promovida pelos iECA/BRA. Descartamos essa opção.",

        "<strong>❌ INCORRETA.</strong><br><br><strong>📌 O erro principal:</strong> Manter o tratamento inalterado é uma conduta NEGLIGENTE, pois a paciente tem PA acima da meta (< 130/80 mmHg para DRC com albuminúria) e já apresenta lesão renal com microalbuminúria progressiva.<br><br><strong>🔍 O que é preciso fazer?</strong><br>Embora a adesão ao tratamento seja sempre importante, o problema aqui não é falta de adesão (a paciente está usando os medicamentos prescritos). O problema é que o esquema atual é <strong>insuficiente</strong> para controlar a PA e, mais importante, não inclui um fármaco que bloqueie o sistema renina-angiotensina-aldosterona (iECA/BRA), que é a classe mais eficaz para reduzir a albuminúria e retardar a progressão da DRC.<br><br><strong>✅ Conduta correta:</strong> Ajustar a terapia adicionando iECA/BRA, não apenas \"trabalhar a adesão\". Essa alternativa é uma pegadinha para quem não reconhece a indicação obrigatória desses medicamentos na DRC albuminúrica."
    ]
},
{
    prova: "Revalida 2022",
    area: "Cirurgia",
    tema: "Abdome agudo inflamatório",
    pergunta: "Homem de 55 anos de idade apresenta quadro de dor em fossa ilíaca esquerda. No exame físico, apresentava bom estado geral, frequência cardíaca de 90 batimentos por minuto, pressão arterial de 130 × 80 mmHg, frequência respiratória de 20 incursões respiratórias por minuto e temperatura axilar de 37,9 °C. O paciente realizou tomografia de abdome e pelve, que mostrou ausência de líquido livre e gás na cavidade peritoneal, discreta distensão de alças de delgado e cólons direito e transverso, espessamento de cólon descendente e abscesso pericolônico de 6 cm próximo à goteira parietocólica esquerda. Nesse caso, qual é a melhor conduta imediata?",
    alternativas: [
        "Internação e antibioticoterapia venosa exclusiva.",
        "Antibioticoterapia venosa e drenagem do abscesso.",
        "Alta hospitalar e antibioticoterapia oral ambulatorial.",
        "Laparotomia exploradora e procedimento de Hartmann."
    ],
    correta: 1,
    comentarios: [
        "<strong>❌ INCORRETA.</strong><br><br><strong>📌 O erro principal:</strong> A antibioticoterapia venosa exclusiva (sem drenagem) é indicada para abscessos pericolônicos com diâmetro < 4-5 cm ou para casos de diverticulite não complicada (Hinchey I). No entanto, o abscesso descrito na TC tem <strong>6 cm de diâmetro</strong>, o que ultrapassa esse limite.<br><br><strong>🔍 Por que o ATB isolado é insuficiente?</strong><br>Um abscesso de 6 cm já apresenta uma coleção purulenta organizada e encapsulada. A antibioticoterapia venosa tem dificuldade de penetrar nessa cavidade fechada em concentrações eficazes, e o pus no interior da coleção não é drenado espontaneamente. Deixar apenas com ATB aumenta o risco de falha terapêutica, sepse e progressão para peritonite.<br><br><strong>✅ Conduta correta para Hinchey I/II:</strong> Para abscessos > 4-5 cm, a conduta padrão-ouro é <strong>ATB venoso + drenagem guiada por imagem</strong> (TC ou USG), conforme veremos na alternativa correta.",

        "<strong>✅ ALTERNATIVA CORRETA.</strong><br><br><strong>📌 Motivo principal:</strong> O quadro é de uma diverticulite aguda complicada com abscesso pericólico de 6 cm, sem sinais de peritonite generalizada (ausência de líquido livre ou gás na TC) e com estabilidade hemodinâmica (PA, FC e FR normais). Isso se enquadra na <strong>classificação de Hinchey II</strong> (abscesso pélvico ou abdominal confinado).<br><br><strong>🔬 Raciocínio passo a passo e fundamentação:</strong><br>1) <strong>Diagnóstico:</strong> A diverticulite aguda de cólon descendente/esquerdo é a principal hipótese pela dor em FIE e espessamento colônico na TC.<br>2) <strong>Classificação de Hinchey:</strong> Abscesso pericólico de 6 cm, sem peritonite difusa = <strong>Hinchey II</strong>. Neste estágio, as diretrizes da WSES (World Society of Emergency Surgery) e da ASCRS (American Society of Colon and Rectal Surgeons) recomendam <strong>ATB venoso de amplo espectro + drenagem percutânea guiada por imagem</strong> (TC ou USG) como tratamento de escolha, sempre que acessível e seguro.<br>3) A drenagem percutânea é <strong>minimamente invasiva</strong>, drena o pus, descomprime a coleção e permite que o ATB atue no tecido adjacente, evitando uma laparotomia de urgência.<br><br><strong>💡 Dica de ouro:</strong> Lembre-se: <em>\"Abscesso > 4-5 cm = drena + ATB; < 4 cm = ATB exclusivo; peritonite difusa ou sepse grave = laparotomia (Hartmann ou anastomose primária)\"</em>. Essa é uma das regras mais cobradas em provas de cirurgia!",

        "<strong>❌ INCORRETA.</strong><br><br><strong>📌 O erro principal:</strong> A alta hospitalar com antibioticoterapia oral ambulatorial é uma conduta exclusiva para casos de <strong>diverticulite NÃO complicada (Hinchey 0 ou I)</strong>, ou seja, pacientes sem abscesso, sem perfuração, sem sepse e com tolerância à dieta oral.<br><br><strong>🔍 Por que essa conduta é perigosa aqui?</strong><br>O paciente tem um abscesso de 6 cm, com febre (37,9°C), sinais de resposta inflamatória sistêmica (leucocitose provável) e necessita de ATB <strong>venoso</strong> (alta biodisponibilidade garantida). Além disso, o abscesso precisa ser drenado, o que impossibilita o tratamento ambulatorial.<br><br><strong>⚠️ Cuidado:</strong> Mandar um paciente com abscesso pericólico para casa com ATB oral é um erro médico grave, que pode levar à evolução para sepse, perfuração livre e peritonite fatal. Descartamos essa opção com segurança.",

        "<strong>❌ INCORRETA.</strong><br><br><strong>📌 O erro principal:</strong> A laparotomia exploradora com procedimento de Hartmann (colectomia do cólon descendente com colostomia terminal e fechamento do reto) é uma cirurgia de grande porte e mutiladora, reservada para situações de <strong>emergência absoluta</strong>: peritonite generalizada (Hinchey III/IV), falha da drenagem percutânea, sepse grave refratária ou instabilidade hemodinâmica.<br><br><strong>🔍 Por que é DESPROPORCIONAL e errada aqui?</strong><br>O paciente está CLINICAMENTE ESTÁVEL (FC 90, PA 130x80, bom estado geral) e a TC mostrou ausência de líquido livre ou gás peritoneal, ou seja, NÃO há peritonite difusa. Iniciar uma laparotomia de urgência para Hartmann em um paciente estável, com abscesso localizado, fere o princípio do <strong>menor dano</strong> e expõe o paciente a riscos cirúrgicos desnecessários (infecção de ferida, hérnias, complicações da colostomia, longa internação).<br><br><strong>✅ Conduta correta:</strong> Optar pela drenagem percutânea + ATB venoso (alternativa B). Se houver falha da drenagem ou piora clínica, aí sim se cogita a cirurgia. Portanto, essa alternativa está completamente equivocada como conduta imediata."
    ]
},
{
    prova: "Revalida 2022",
    area: "Pediatria",
    tema: "Crescimento e desenvolvimento",
    pergunta: "Adolescente de 11 anos, sexo masculino, em consulta de rotina com pediatra, refere ser um dos menores alunos da sua sala. O crescimento do paciente nos últimos 6 meses foi de 2,5 cm. A projeção de sua estatura vai ao encontro do canal familiar (pai mede 161 cm e mãe mede 150 cm). No gráfico estatura × idade, situa-se entre o escore-z −2 e −3. Exame físico sem alterações, sem características de doenças gênicas ou cromossômicas, estadiamento puberal de Tanner G2 P1. Conforme radiografia de mão e punho esquerdos, a idade óssea do paciente é de 11 anos.",
    alternativas: [
        "Puberdade atrasada.",
        "Baixa estatura familiar.",
        "Reduzida velocidade de crescimento.",
        "Idade óssea compatível com distúrbio constitucional de estatura."
    ],
    correta: 1,
    comentarios: [
        "<strong>❌ INCORRETA.</strong><br><br><strong>📌 O erro principal:</strong> A puberdade atrasada é definida pela ausência de características sexuais secundárias até os 14 anos em meninos (ou 13 anos em meninas). O paciente tem 11 anos e já apresenta <strong>estadiamento G2P1</strong> (gênito 2 e pêlos 1), o que indica que a puberdade JÁ INICIOU, sendo totalmente normal para a faixa etária (média de início em meninos é 11,5-12 anos).<br><br><strong>🔍 Desconstruindo a confusão:</strong> Muitos alunos confundem baixa estatura com puberdade atrasada, mas são conceitos diferentes. Na puberdade atrasada, o paciente tem baixa estatura POR CAUSA do atraso puberal (o estirão do crescimento ainda não ocorreu). Aqui, a puberdade já começou, então a baixa estatura tem outra origem.<br><br><strong>⚠️ Dica:</strong> Em meninos, Tanner G2 (volume testicular > 4 ml ou diâmetro > 2,5 cm) é o marco do início puberal. Aos 11 anos, isso é NORMAL, não atrasado. A puberdade atrasada só seria considerada se não houvesse G2 até os 14 anos completos.",

        "<strong>✅ ALTERNATIVA CORRETA.</strong><br><br><strong>📌 Motivo principal:</strong> Este é um caso clássico de baixa estatura familiar (ou genética), também chamada de <em>\"baixa estatura variante normal\"</em>. O diagnóstico é baseado em 3 pilares fundamentais, todos presentes aqui:<br><br><strong>🔬 Raciocínio passo a passo:</strong><br>1) <strong>Canal familiar:</strong> A estatura-alvo da criança (calculada pela fórmula: altura do pai + altura da mãe + 13, dividido por 2, para meninos) é de aproximadamente 162-165 cm. O paciente está projetado para essa faixa (\"vai ao encontro do canal familiar\"), ou seja, sua baixa estatura é COMPATÍVEL com a baixa estatura dos pais.<br>2) <strong>Velocidade de crescimento normal:</strong> 2,5 cm em 6 meses = 5 cm/ano, o que é adequado para a idade (a velocidade mínima esperada entre 3 anos e o estirão puberal é de cerca de 5 cm/ano). Portanto, NÃO há redução da velocidade de crescimento.<br>3) <strong>Idade óssea compatível com a idade cronológica:</strong> A radiografia de mão e punho mostrou idade óssea de 11 anos, EXATAMENTE IGUAL à idade real (11 anos). Isso descarta atraso ósseo (que seria característico do Distúrbio Constitucional do Crescimento e Puberdade - DCCP).<br>4) <strong>Puberdade no tempo adequado:</strong> Tanner G2P1 aos 11 anos é completamente normal, confirmando que o desenvolvimento está dentro do esperado.<br><br><strong>💡 Dica de ouro para a prova:</strong> <em>\"Baixa estatura + pais baixos + velocidade de crescimento normal + idade óssea compatível + puberdade normal = baixa estatura familiar\"</em>. NÃO se deve tratar com hormônio do crescimento (GH) nesses casos, pois a estatura final será adequada ao alvo genético. O manejo é apenas tranquilização e acompanhamento.",

        "<strong>❌ INCORRETA.</strong><br><br><strong>📌 O erro principal:</strong> A \"reduzida velocidade de crescimento\" é um ACHADO CLÍNICO (um dado) e não um diagnóstico etiológico. Além disso, ela NÃO ESTÁ PRESENTE neste caso. A velocidade de crescimento do paciente nos últimos 6 meses foi de 2,5 cm, o que equivale a 5 cm/ano.<br><br><strong>🔍 O que seria considerado velocidade reduzida?</strong><br>A velocidade de crescimento é considerada reduzida quando está abaixo do percentil 25 para a idade e sexo, ou quando é inferior a <strong>5 cm/ano</strong> em crianças entre 3 anos e o início da puberdade. No caso, exatamente 5 cm/ano, no limite inferior do normal. Isso não caracteriza redução patológica, especialmente considerando que a criança está em início de puberdade (quando a velocidade começa a acelerar).<br><br><strong>⚠️ Atenção:</strong> A questão pergunta o DIAGNÓSTICO, e não um dado isolado. Reduzida velocidade de crescimento é um sinal, não uma doença. A alternativa tenta confundir o aluno que não calcula a velocidade corretamente. Descartamos.",

        "<strong>❌ INCORRETA.</strong><br><br><strong>📌 O erro principal:</strong> O Distúrbio Constitucional do Crescimento e Puberdade (DCCP) – também chamado de <em>\"atraso constitucional do crescimento e puberdade\"</em> – é caracterizado por uma <strong>idade óssea ATRASADA em relação à idade cronológica</strong> (geralmente 1 a 2 anos de atraso), acompanhada de puberdade tardia. O paciente em questão tem <strong>idade óssea de 11 anos para 11 anos de idade cronológica</strong>, ou seja, <strong>NÃO HÁ ATRASO</strong>.<br><br><strong>🔍 Por que essa confusão é comum?</strong><br>Tanto a baixa estatura familiar quanto o DCCP são causas de baixa estatura, mas o DCCP cursa com atraso ósseo e puberal, enquanto a baixa estatura familiar tem idade óssea normal e puberdade na época certa. Este é o PRINCIPAL PONTO DE DIFERENCIAÇÃO entre as duas condições.<br><br><strong>✅ O que caracterizaria DCCP?</strong><br>Um paciente com DCCP teria: idade óssea < idade cronológica (ex: 9 anos para 11 anos de idade), puberdade atrasada (Tanner G1/P1 aos 11 anos) e velocidade de crescimento reduzida, mas com potencial de crescimento tardio e estirão prolongado. Como isso NÃO está presente, a alternativa está incorreta.<br><br><strong>💡 Macete infalível:</strong> <em>\"Idade óssea atrasada = DCCP; idade óssea normal = baixa estatura familiar\"</em>. Essa é a regra de ouro para o diagnóstico diferencial! Não erre mais essa na prova."
    ]
},
{
    prova: "Revalida 2022",
    area: "Ginecologia e Obstetrícia",
    tema: "Sangramento Uterino Anormal",
    pergunta: "Mulher de 23 anos de idade procurou o ambulatório de ginecologia, com queixa de aumento da intensidade e duração do fluxo menstrual há 8 meses. Nulípara, tem como antecedentes três abortos espontâneos, nos quais não precisou realizar curetagem uterina. No exame físico, não apresentou qualquer alteração. Apresentou os seguintes exames complementares recentes: Colpocitologia oncológica: alterações celulares benignas reativas ou reparativas. Ultrassonografia: volume uterino de 88 cm3, eco endometrial heterogêneo de 36 mm (normalidade considerada até 15 mm) com lesão hiperecoica de contornos regulares na cavidade uterina. Anexos sem alterações ultrassonográficas. Considerando a história clínica e os exames físico e complementar da paciente, assinale a opção que apresenta a hipótese diagnóstica e a conduta adequada, respectivamente.",
    alternativas: [
        "Patologia cervical; colposcopia.",
        "Gestação ectópica; laparotomia exploratória.",
        "Miomatose uterina; laparoscopia diagnóstica.",
        "Pólipo endometrial; histeroscopia diagnóstica."
    ],
    correta: 3,
    comentarios: [
        "<strong>❌ INCORRETA.</strong><br><br><strong>📌 O erro principal:</strong> A colposcopia é um exame que visualiza o COLO UTERINO (ectocérvice e endocérvice) após aplicação de ácido acético e lugol, sendo indicado para investigar <strong>alterações citopatológicas do colo</strong> (ex: NIC, HPV, carcinoma). No entanto, a colpocitologia oncológica (Papanicolau) da paciente mostrou apenas <strong>\"alterações celulares benignas reativas ou reparativas\"</strong>, ou seja, NÃO há lesão cervical suspeita.<br><br><strong>🔍 Por que a colposcopia é inútil aqui?</strong><br>A paciente tem sangramento uterino anormal e alteração ENDOMETRIAL (eco heterogêneo de 36 mm com lesão hiperecoica na cavidade). Essas alterações são na CAVIDADE UTERINA e NÃO são visualizadas pela colposcopia, que só avalia o colo. A lesão é intrauterina, então o exame correto para visualizar a cavidade é a <strong>histeroscopia</strong>.<br><br><strong>⚠️ Dica:</strong> Colposcopia ≠ Histeroscopia. Colposcopia = colo; Histeroscopia = cavidade uterina. Essa confusão é clássica em provas!",

        "<strong>❌ INCORRETA.</strong><br><br><strong>📌 O erro principal:</strong> A gestação ectópica é caracterizada pela implantação do embrião FORA da cavidade uterina (tuba, ovário, cavidade abdominal). Os sintomas clássicos são: atraso menstrual, dor pélvica, sangramento vaginal escuro, e pode evoluir com choque hemorrágico por rotura tubária. No entanto, a paciente NÃO tem nenhuma dessas características.<br><br><strong>🔍 O que contradiz a gestação ectópica?</strong><br>1) A paciente teve ABORTOS ESPONTÂNEOS prévios (isso indica que ela engravida e o embrião se implanta DENTRO do útero, o que descarta infertilidade tubária).<br>2) A ultrassonografia mostra a CAVIDADE UTERINA com lesão hiperecoica e endométrio espessado (36 mm) – na gestação ectópica, o útero geralmente está vazio (sem saco gestacional) ou com pseudo-saco, e anexos podem mostrar massa tubária. Anexos estão NORMAIS no USG.<br>3) Não há queixa de dor pélvica aguda, atraso menstrual ou β-hCG positivo (que sequer foi citado).<br><br><strong>✅ Conduta correta:</strong> Na suspeita de gestação ectópica estável, o diagnóstico é com β-hCG seriado e USG transvaginal, e a conduta seria metotrexato ou cirurgia (salpingectomia). Mas aqui não há nenhuma indicação disso. Descartamos com segurança.",

        "<strong>❌ INCORRETA.</strong><br><br><strong>📌 O erro principal:</strong> A miomatose uterina (presença de miomas) é uma causa comum de sangramento uterino anormal, mas os miomas têm características ultrassonográficas específicas: são lesões <strong>hipoecoicas (escuras)</strong>, com bordas bem definidas, geralmente arredondadas, e podem ser submucosos, intramurais ou subserosos. O USG da paciente mostrou uma <strong>lesão hiperecoica (branca) na cavidade</strong>, o que é muito mais sugestivo de pólipo endometrial do que de mioma.<br><br><strong>🔍 Por que a laparoscopia é inadequada?</strong><br>1) A laparoscopia é um procedimento que visualiza a cavidade abdominal e a superfície externa do útero (serosa). Ela NÃO visualiza a CAVIDADE UTERINA interna. Mesmo que a paciente tivesse miomas submucosos (que causam sangramento), o diagnóstico e tratamento desses miomas é feito por <strong>histeroscopia cirúrgica (miomectomia histeroscópica)</strong>, e não por laparoscopia.<br>2) A paciente NÃO tem miomas descritos no USG, e a lesão hiperecoica intrauterina aponta para pólipo.<br><br><strong>💡 Diferença crucial:</strong> A laparoscopia serve para investigar causas extrauterinas (endometriose, aderências, cistos ovarianos) ou para realizar procedimentos como laqueadura. A histeroscopia é a via de acesso à CAVIDADE, onde está a lesão da paciente. Não confunda as duas!",

        "<strong>✅ ALTERNATIVA CORRETA.</strong><br><br><strong>📌 Motivo principal:</strong> Este é um caso clássico de <strong>PÓLIPO ENDOMETRIAL</strong>, uma lesão benigna da mucosa uterina, comum em mulheres em idade reprodutiva, que se apresenta como uma projeção pediculada ou séssil para dentro da cavidade uterina. Os achados que confirmam essa hipótese são:<br><br><strong>🔬 Raciocínio passo a passo:</strong><br>1) <strong>Sangramento uterino anormal (SUA):</strong> A paciente tem aumento da intensidade e duração do fluxo (menorragia) há 8 meses. Pólipos endometriais frequentemente causam sangramento irregular ou excessivo, especialmente em nulíparas.<br>2) <strong>USG com endométrio espessado (36 mm):</strong> O valor normal para a fase lútea ou proliferativa é até 15 mm. Um endométrio > 20 mm já é considerado suspeito e indica a necessidade de investigação endometrial. O espessamento heterogêneo com lesão hiperecoica na cavidade é o achado ultrassonográfico típico de pólipo endometrial.<br>3) <strong>Abortos espontâneos de repetição:</strong> Pólipos endometriais podem atuar como \"corpo estranho\" intrauterino, interferindo na implantação embrionária e aumentando o risco de abortamento. A associação de SUA + abortos + lesão hiperecoica intrauterina fortalece o diagnóstico de pólipo.<br>4) <strong>Colpocitologia normal:</strong> O exame do colo está normal, o que desvia a atenção para o interior do útero.<br><br><strong>✅ Conduta adequada:</strong> A <strong>HISTEROSCOPIA DIAGNÓSTICA</strong> é o padrão-ouro para avaliação da cavidade uterina. Ela permite a visualização direta do pólipo, sua localização exata, tamanho, e a realização de <strong>biópsia ou polipectomia (ressecção do pólipo)</strong> no mesmo procedimento (histeroscopia cirúrgica). É um procedimento minimamente invasivo, ambulatorial, que não requer incisão, e é especialmente indicado para nulíparas, pois preserva a integridade do colo e da cavidade uterina.<br><br><strong>💡 Dica de ouro:</strong> <em>\"Sangramento + endométrio espessado + lesão hiperecoica intrauterina + abortos de repetição = PÓLIPO ENDOMETRIAL; conduta = HISTEROSCOPIA\"</em>. Fique atento: a curetagem uterina (ou histeroscopia?) já foi superada como método diagnóstico; a histeroscopia é o padrão ouro porque permite visualização direta e ressecção guiada, evitando curetagem às cegas que pode deixar fragmentos."
    ]
},
{
    prova: "Revalida 2022",
    area: "Clinica Médica",
    tema: "Transtornos psiquiatricos",
    pergunta: "Uma mulher de 43 anos compareceu a uma unidade de saúde da família, com queixas de estresse e ansiedade. Informa que iniciou, há 10 semanas, o tratamento com sertralina 50 mg/dia e que, nesse período, apresentou uma melhora discreta dos sintomas. Entretanto, nas últimas 4 semanas, tem tido ataques recorrentes de ansiedade intensa quando precisa sair de casa, o que tem limitado seu desempenho, inclusive para atividades do dia a dia, como ir ao supermercado e buscar os filhos no colégio. Conforme relato dela, no dia desta consulta, teve muita dificuldade para sair de casa. Nesse caso, qual é a conduta adequada?",
    alternativas: [
        "Prescrever um benzodiazepínico e encaminhar a paciente para a emergência de um hospital psiquiátrico.",
        "Manter a sertralina na dose atual e monitorar a evolução da paciente.",
        "Encaminhar a paciente para um serviço com psicoterapia estruturada e reavaliar a medicação em uso.",
        "Substituir a sertralina por fluoxetina 20 mg, clonazepam 0,5 mg e clorpromazina 25 mg."
    ],
    correta: 2,
    comentarios: [
        "<strong>❌ INCORRETA.</strong><br><br><strong>📌 O erro principal:</strong> A prescrição de benzodiazepínico (BZD) associada ao encaminhamento para emergência psiquiátrica é uma conduta <strong>DESPROPORCIONAL</strong> e desnecessária neste caso. A paciente apresenta ansiedade intensa e agorafobia (medo de sair de casa), mas NÃO há sinais de agitação psicomotora grave, crise de pânico no momento da consulta, ideação suicida, comportamento de risco ou comprometimento orgânico.<br><br><strong>🔍 Quando usar BZD e emergência?</strong><br>Benzodiazepínicos são indicados como <strong>medicação de resgate pontual</strong> em crises agudas de pânico, mas nunca como conduta isolada ou de primeira linha em um quadro crônico de 4 semanas. O encaminhamento à emergência psiquiátrica é reservado para <strong>urgências psiquiátricas</strong>: risco de suicídio iminente, estado confusional agudo, agressividade incontrolável ou síndrome de abstinência grave. A paciente está estável, com boa insight e procurou ajuda na UBS, portanto não cabe emergência.<br><br><strong>⚠️ Fique atento:</strong> BZDs têm potencial de dependência e devem ser usados com cautela. Prescrever e mandar para a emergência seria uma conduta iatrogênica, que medicaliza excessivamente e sobrecarrega o sistema, sem oferecer o tratamento adequado de base (psicoterapia + ajuste do ISRS).",

        "<strong>❌ INCORRETA.</strong><br><br><strong>📌 O erro principal:</strong> Manter a sertralina na dose atual (50 mg) e apenas \"monitorar\" a paciente é uma conduta <strong>NEGLIGENTE</strong> e insuficiente diante da piora clínica evidente. A paciente já está em uso do ISRS há <strong>10 semanas (2,5 meses)</strong>, tempo mais que suficiente para observar uma resposta terapêutica plena (que geralmente ocorre entre 4 a 6 semanas).<br><br><strong>🔍 O que a evolução clínica indica?</strong><br>1) A paciente apresentou <strong>melhora discreta</strong> nos primeiros 10 semanas, mas <strong>piorou significativamente</strong> nas últimas 4 semanas, com o desenvolvimento de <strong>agorafobia</strong> (ansiedade ao sair de casa) e comprometimento funcional grave (não consegue ir ao supermercado ou buscar os filhos).<br>2) A dose de 50 mg de sertralina é uma dose inicial, e muitas vezes é insuficiente para o controle de transtorno de pânico com agorafobia, sendo necessário <strong>ajuste posológico</strong> (aumento da dose, ex: 100-150 mg) ou troca/substituição. Não aumentar a dose diante da piora é perder uma oportunidade terapêutica.<br>3) Além da farmacoterapia, o paciente com agorafobia se beneficia imensamente da <strong>psicoterapia estruturada</strong>, especialmente a Terapia Cognitivo-Comportamental (TCC) com exposição gradual, que é o padrão-ouro para fobias.<br><br><strong>✅ Conduta correta:</strong> Otimizar a medicação E encaminhar para psicoterapia (alternativa C). Manter a dose atual seria subtratar e prolongar o sofrimento da paciente.",

        "<strong>✅ ALTERNATIVA CORRETA.</strong><br><br><strong>📌 Motivo principal:</strong> Este é o manejo ideal para um paciente em atenção primária com transtorno de pânico/agorafobia que não respondeu plenamente ao ISRS. A conduta combina duas abordagens complementares e essenciais: <strong>otimização farmacológica + psicoterapia estruturada</strong>.<br><br><strong>🔬 Raciocínio passo a passo:</strong><br>1) <strong>Reavaliar a medicação em uso:</strong> A sertralina 50 mg por 10 semanas produziu apenas melhora discreta, e o quadro piorou com sintomas fóbicos. A conduta farmacológica apropriada é <strong>aumentar a dose</strong> da sertralina (geralmente para 100-150 mg/dia, até o máximo de 200 mg), que é a estratégia de primeira linha para transtorno de pânico que não responde. Se mesmo com o aumento não houver resposta, cogita-se trocar por outro ISRS (ex: paroxetina) ou dupla ação (ex: venlafaxina). <strong>Nunca</strong> se deve trocar ou descontinuar o tratamento sem uma tentativa de otimização da dose.<br>2) <strong>Encaminhar para psicoterapia estruturada:</strong> A agorafobia e as crises de ansiedade ao sair de casa têm um forte componente comportamental e cognitivo. A <strong>Terapia Cognitivo-Comportamental (TCC)</strong> com exposição gradual é a psicoterapia com maior evidência científica para transtorno de pânico e agorafobia (Classe I, Nível A). O encaminhamento deve ser para um serviço de psicologia no CAPS, ambulatório de saúde mental ou até mesmo na própria UBS se houver psicólogo disponível com essa expertise.<br><br><strong>💡 Dica de ouro:</strong> <em>\"ISRS com resposta parcial + agorafobia = aumentar dose + encaminhar para TCC\"</em>. O tratamento combinado (fármaco + psicoterapia) é superior a qualquer uma das abordagens isoladas. Essa é a conduta consagrada nas diretrizes da Associação Brasileira de Psiquiatria (ABP) e da APA (American Psychiatric Association).",

        "<strong>❌ INCORRETA.</strong><br><br><strong>📌 O erro principal:</strong> Esta alternativa é um verdadeiro <strong>\"mau exemplo\"</strong> de polifarmácia irracional e iatrogênica. Substituir a sertralina por fluoxetina (que também é um ISRS) sem antes aumentar a dose da sertralina ou fazer um desmame adequado é uma conduta incoerente e sem fundamento científico.<br><br><strong>🔍 Desmontando os erros um a um:</strong><br>1) <strong>Troca de ISRS sem lógica:</strong> Sertralina e fluoxetina são da mesma classe (ISRS). Se a sertralina não funcionou ou funcionou parcialmente em 50 mg, o correto é <strong>AUMENTAR A DOSE</strong>, e não trocar por outro ISRS (que tem mecanismo de ação idêntico e pode levar tempo para fazer efeito, além de risco de síndrome serotoninérgica com a sobreposição).<br>2) <strong>Clonazepam 0,5 mg:</strong> O uso de benzodiazepínico pode ser considerado como adjuvante por curto período em crises, mas <strong>não deve ser prescrito de rotina como parte do esquema fixo</strong>, pois gera dependência, tolerância e efeito rebote. Deve ser uma ferramenta de resgate, não uma prescrição regular.<br>3) <strong>Clorpromazina 25 mg (neuroléptico antipsicótico):</strong> Este é o erro mais grave. A clorpromazina é um <strong>antipsicótico típico</strong>, com potentes efeitos colaterais (sedação excessiva, hipotensão postural, efeitos extrapiramidais, discinesia tardia). Ela NÃO TEM INDICAÇÃO para transtorno de ansiedade ou agorafobia, a menos que haja sintomas psicóticos associados (o que não é o caso). Prescrever um neuroléptico para uma paciente com ansiedade é um erro grosseiro e perigoso.<br><br><strong>⚠️ Conclusão:</strong> Essa alternativa representa uma <strong>conduta completamente inadequada</strong>, que exporia a paciente a efeitos colaterais desnecessários, polifarmácia descontrolada e risco de dependência, sem oferecer o tratamento correto (psicoterapia + otimização do ISRS). Descartamos com absoluta certeza."
    ]
}
];